---
galaxy_info:
  author: Shoma Nishitateno
  description: Installs l2tp-ipsec vpn client.
  license: "license MIT"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - 7
        - 6
  galaxy_tags: []

  #dependencies:
  #  - shomatan.epel
