---

galaxy_info:
  author: Maxim Baranov <maksim.baranov@gmail.com>
  description: Alertmanager Bot (https://github.com/metalmatze/alertmanager-bot)
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - stretch
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - monitoring
    - prometheus
    - alertmanager
    - telegram

dependencies: []
